language: c
sudo: false

notifications:
  webhooks:
    urls:
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

env:
    global:
    - BYOND_MAJOR="514"
    - BYOND_MINOR="1582"
    - DM_BUILDFILE="fortune13.dme"

cache:
  directories:
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}

addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386

before_install:
  - chmod +x tools/ci/install_spaceman_dmm.sh

install:
  - tools/ci/install_spaceman_dmm.sh dreamchecker
      
before_script:
  - chmod +x tools/ci/check_filedirs.sh
  - chmod +x tools/ci/install-byond.sh
  - tools/ci/install-byond.sh

after_success:
  - chmod +x ./send-to-discord.sh
  - ./send-to-discord.sh success $WEBHOOK_URL

after_failure:
  - chmod +x ./send-to-discord.sh
  - ./send-to-discord.sh failure $WEBHOOK_URL

script:
  - tools/ci/check_filedirs.sh ${DM_BUILDFILE}
  - (! grep 'step_[xy]' maps/**/*.dmm)
  - ~/dreamchecker
  - source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup
  - DreamMaker ${DM_BUILDFILE}
